package com.hstd.exchange.entity.dao;

import com.hstd.exchange.entity.model.FaReceiptAdviceExample;
import java.util.List;
import java.sql.SQLException;
import com.hstd.exchange.entity.model.FaReceiptAdvice;
import com.hstd.exchange.entity.model.FaReceiptAdviceKey;

public interface FaReceiptAdviceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    void insert(FaReceiptAdvice record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    int updateByPrimaryKey(FaReceiptAdvice record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    List selectByExample(FaReceiptAdviceExample example, String orderByClause) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    List selectByExample(FaReceiptAdviceExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    FaReceiptAdvice selectByPrimaryKey(FaReceiptAdviceKey key) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    int deleteByExample(FaReceiptAdviceExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    int deleteByPrimaryKey(FaReceiptAdviceKey key) throws SQLException;
}
