package com.hstd.exchange.entity.model;


public class FaReceiptAdviceExample extends FaReceiptAdvice {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int receiptAdviceId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int receiptAdviceNo_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int paymentAdviceId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int paymentMemberId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorMemberId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int receiptMemberId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorItemNo_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int receivableAmt_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int certFee_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorFee_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int balanceAmt_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int transferringAmt_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int transferredAmt_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int adviceStatus_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorStatus_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int transferStatus_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int remark_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int operatorId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int createdDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int confirmOperatorId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int confirmDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int cancelOperatorId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int cancelDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorOperatorId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorConfirmDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int factorUnconfirmReason_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int attachmentInfo1_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int attachmentInfo2_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int attachmentInfo3_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int interestRate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private int feeRate_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getReceiptAdviceId_Indicator() {
        return receiptAdviceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptAdviceId_Indicator(int receiptAdviceId_Indicator) {
        this.receiptAdviceId_Indicator = receiptAdviceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getReceiptAdviceNo_Indicator() {
        return receiptAdviceNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptAdviceNo_Indicator(int receiptAdviceNo_Indicator) {
        this.receiptAdviceNo_Indicator = receiptAdviceNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getPaymentAdviceId_Indicator() {
        return paymentAdviceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setPaymentAdviceId_Indicator(int paymentAdviceId_Indicator) {
        this.paymentAdviceId_Indicator = paymentAdviceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getPaymentMemberId_Indicator() {
        return paymentMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setPaymentMemberId_Indicator(int paymentMemberId_Indicator) {
        this.paymentMemberId_Indicator = paymentMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorMemberId_Indicator() {
        return factorMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorMemberId_Indicator(int factorMemberId_Indicator) {
        this.factorMemberId_Indicator = factorMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getReceiptMemberId_Indicator() {
        return receiptMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptMemberId_Indicator(int receiptMemberId_Indicator) {
        this.receiptMemberId_Indicator = receiptMemberId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorItemNo_Indicator() {
        return factorItemNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorItemNo_Indicator(int factorItemNo_Indicator) {
        this.factorItemNo_Indicator = factorItemNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getReceivableAmt_Indicator() {
        return receivableAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceivableAmt_Indicator(int receivableAmt_Indicator) {
        this.receivableAmt_Indicator = receivableAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getCertFee_Indicator() {
        return certFee_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCertFee_Indicator(int certFee_Indicator) {
        this.certFee_Indicator = certFee_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorFee_Indicator() {
        return factorFee_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorFee_Indicator(int factorFee_Indicator) {
        this.factorFee_Indicator = factorFee_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getBalanceAmt_Indicator() {
        return balanceAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setBalanceAmt_Indicator(int balanceAmt_Indicator) {
        this.balanceAmt_Indicator = balanceAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getTransferringAmt_Indicator() {
        return transferringAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferringAmt_Indicator(int transferringAmt_Indicator) {
        this.transferringAmt_Indicator = transferringAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getTransferredAmt_Indicator() {
        return transferredAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferredAmt_Indicator(int transferredAmt_Indicator) {
        this.transferredAmt_Indicator = transferredAmt_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getAdviceStatus_Indicator() {
        return adviceStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAdviceStatus_Indicator(int adviceStatus_Indicator) {
        this.adviceStatus_Indicator = adviceStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorStatus_Indicator() {
        return factorStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorStatus_Indicator(int factorStatus_Indicator) {
        this.factorStatus_Indicator = factorStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getTransferStatus_Indicator() {
        return transferStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferStatus_Indicator(int transferStatus_Indicator) {
        this.transferStatus_Indicator = transferStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getRemark_Indicator() {
        return remark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setRemark_Indicator(int remark_Indicator) {
        this.remark_Indicator = remark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getOperatorId_Indicator() {
        return operatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setOperatorId_Indicator(int operatorId_Indicator) {
        this.operatorId_Indicator = operatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getCreatedDate_Indicator() {
        return createdDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCreatedDate_Indicator(int createdDate_Indicator) {
        this.createdDate_Indicator = createdDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getConfirmOperatorId_Indicator() {
        return confirmOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setConfirmOperatorId_Indicator(int confirmOperatorId_Indicator) {
        this.confirmOperatorId_Indicator = confirmOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getConfirmDate_Indicator() {
        return confirmDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setConfirmDate_Indicator(int confirmDate_Indicator) {
        this.confirmDate_Indicator = confirmDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getCancelOperatorId_Indicator() {
        return cancelOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCancelOperatorId_Indicator(int cancelOperatorId_Indicator) {
        this.cancelOperatorId_Indicator = cancelOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getCancelDate_Indicator() {
        return cancelDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCancelDate_Indicator(int cancelDate_Indicator) {
        this.cancelDate_Indicator = cancelDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorOperatorId_Indicator() {
        return factorOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorOperatorId_Indicator(int factorOperatorId_Indicator) {
        this.factorOperatorId_Indicator = factorOperatorId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorConfirmDate_Indicator() {
        return factorConfirmDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorConfirmDate_Indicator(int factorConfirmDate_Indicator) {
        this.factorConfirmDate_Indicator = factorConfirmDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFactorUnconfirmReason_Indicator() {
        return factorUnconfirmReason_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorUnconfirmReason_Indicator(int factorUnconfirmReason_Indicator) {
        this.factorUnconfirmReason_Indicator = factorUnconfirmReason_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getAttachmentInfo1_Indicator() {
        return attachmentInfo1_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo1_Indicator(int attachmentInfo1_Indicator) {
        this.attachmentInfo1_Indicator = attachmentInfo1_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getAttachmentInfo2_Indicator() {
        return attachmentInfo2_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo2_Indicator(int attachmentInfo2_Indicator) {
        this.attachmentInfo2_Indicator = attachmentInfo2_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getAttachmentInfo3_Indicator() {
        return attachmentInfo3_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo3_Indicator(int attachmentInfo3_Indicator) {
        this.attachmentInfo3_Indicator = attachmentInfo3_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getInterestRate_Indicator() {
        return interestRate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setInterestRate_Indicator(int interestRate_Indicator) {
        this.interestRate_Indicator = interestRate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public int getFeeRate_Indicator() {
        return feeRate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table pj_fa_receipt_advice
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFeeRate_Indicator(int feeRate_Indicator) {
        this.feeRate_Indicator = feeRate_Indicator;
    }
}
