package com.hstd.exchange.entity.model;

import java.util.Date;

public class FaReceiptAdvice extends FaReceiptAdviceKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.RECEIPT_ADVICE_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String receiptAdviceNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.PAYMENT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long paymentAdviceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.PAYMENT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long paymentMemberId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long factorMemberId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.RECEIPT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long receiptMemberId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_ITEM_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String factorItemNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.RECEIVABLE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long receivableAmt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CERT_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long certFee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long factorFee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.BALANCE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long balanceAmt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.TRANSFERRING_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long transferringAmt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.TRANSFERRED_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long transferredAmt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.ADVICE_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String adviceStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String factorStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.TRANSFER_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String transferStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.REMARK
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String operatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CREATED_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private Date createdDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CONFIRM_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String confirmOperatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private Date confirmDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CANCEL_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String cancelOperatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.CANCEL_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private Date cancelDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String factorOperatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private Date factorConfirmDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FACTOR_UNCONFIRM_REASON
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String factorUnconfirmReason;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.ATTACHMENT_INFO1
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String attachmentInfo1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.ATTACHMENT_INFO2
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String attachmentInfo2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.ATTACHMENT_INFO3
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private String attachmentInfo3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.INTEREST_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long interestRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.FEE_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long feeRate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.RECEIPT_ADVICE_NO
     *
     * @return the value of pj_fa_receipt_advice.RECEIPT_ADVICE_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getReceiptAdviceNo() {
        return receiptAdviceNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.RECEIPT_ADVICE_NO
     *
     * @param receiptAdviceNo the value for pj_fa_receipt_advice.RECEIPT_ADVICE_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptAdviceNo(String receiptAdviceNo) {
        if (receiptAdviceNo != null) {
            receiptAdviceNo = receiptAdviceNo.trim();
        }
        this.receiptAdviceNo = receiptAdviceNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.PAYMENT_ADVICE_ID
     *
     * @return the value of pj_fa_receipt_advice.PAYMENT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getPaymentAdviceId() {
        return paymentAdviceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.PAYMENT_ADVICE_ID
     *
     * @param paymentAdviceId the value for pj_fa_receipt_advice.PAYMENT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setPaymentAdviceId(long paymentAdviceId) {
        this.paymentAdviceId = paymentAdviceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.PAYMENT_MEMBER_ID
     *
     * @return the value of pj_fa_receipt_advice.PAYMENT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getPaymentMemberId() {
        return paymentMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.PAYMENT_MEMBER_ID
     *
     * @param paymentMemberId the value for pj_fa_receipt_advice.PAYMENT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setPaymentMemberId(long paymentMemberId) {
        this.paymentMemberId = paymentMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_MEMBER_ID
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getFactorMemberId() {
        return factorMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_MEMBER_ID
     *
     * @param factorMemberId the value for pj_fa_receipt_advice.FACTOR_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorMemberId(long factorMemberId) {
        this.factorMemberId = factorMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.RECEIPT_MEMBER_ID
     *
     * @return the value of pj_fa_receipt_advice.RECEIPT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getReceiptMemberId() {
        return receiptMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.RECEIPT_MEMBER_ID
     *
     * @param receiptMemberId the value for pj_fa_receipt_advice.RECEIPT_MEMBER_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptMemberId(long receiptMemberId) {
        this.receiptMemberId = receiptMemberId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_ITEM_NO
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_ITEM_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getFactorItemNo() {
        return factorItemNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_ITEM_NO
     *
     * @param factorItemNo the value for pj_fa_receipt_advice.FACTOR_ITEM_NO
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorItemNo(String factorItemNo) {
        if (factorItemNo != null) {
            factorItemNo = factorItemNo.trim();
        }
        this.factorItemNo = factorItemNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.RECEIVABLE_AMT
     *
     * @return the value of pj_fa_receipt_advice.RECEIVABLE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getReceivableAmt() {
        return receivableAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.RECEIVABLE_AMT
     *
     * @param receivableAmt the value for pj_fa_receipt_advice.RECEIVABLE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceivableAmt(long receivableAmt) {
        this.receivableAmt = receivableAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CERT_FEE
     *
     * @return the value of pj_fa_receipt_advice.CERT_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getCertFee() {
        return certFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CERT_FEE
     *
     * @param certFee the value for pj_fa_receipt_advice.CERT_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCertFee(long certFee) {
        this.certFee = certFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_FEE
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getFactorFee() {
        return factorFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_FEE
     *
     * @param factorFee the value for pj_fa_receipt_advice.FACTOR_FEE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorFee(long factorFee) {
        this.factorFee = factorFee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.BALANCE_AMT
     *
     * @return the value of pj_fa_receipt_advice.BALANCE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getBalanceAmt() {
        return balanceAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.BALANCE_AMT
     *
     * @param balanceAmt the value for pj_fa_receipt_advice.BALANCE_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setBalanceAmt(long balanceAmt) {
        this.balanceAmt = balanceAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.TRANSFERRING_AMT
     *
     * @return the value of pj_fa_receipt_advice.TRANSFERRING_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getTransferringAmt() {
        return transferringAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.TRANSFERRING_AMT
     *
     * @param transferringAmt the value for pj_fa_receipt_advice.TRANSFERRING_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferringAmt(long transferringAmt) {
        this.transferringAmt = transferringAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.TRANSFERRED_AMT
     *
     * @return the value of pj_fa_receipt_advice.TRANSFERRED_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getTransferredAmt() {
        return transferredAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.TRANSFERRED_AMT
     *
     * @param transferredAmt the value for pj_fa_receipt_advice.TRANSFERRED_AMT
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferredAmt(long transferredAmt) {
        this.transferredAmt = transferredAmt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.ADVICE_STATUS
     *
     * @return the value of pj_fa_receipt_advice.ADVICE_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getAdviceStatus() {
        return adviceStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.ADVICE_STATUS
     *
     * @param adviceStatus the value for pj_fa_receipt_advice.ADVICE_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAdviceStatus(String adviceStatus) {
        if (adviceStatus != null) {
            adviceStatus = adviceStatus.trim();
        }
        this.adviceStatus = adviceStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_STATUS
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getFactorStatus() {
        return factorStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_STATUS
     *
     * @param factorStatus the value for pj_fa_receipt_advice.FACTOR_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorStatus(String factorStatus) {
        if (factorStatus != null) {
            factorStatus = factorStatus.trim();
        }
        this.factorStatus = factorStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.TRANSFER_STATUS
     *
     * @return the value of pj_fa_receipt_advice.TRANSFER_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.TRANSFER_STATUS
     *
     * @param transferStatus the value for pj_fa_receipt_advice.TRANSFER_STATUS
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setTransferStatus(String transferStatus) {
        if (transferStatus != null) {
            transferStatus = transferStatus.trim();
        }
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.REMARK
     *
     * @return the value of pj_fa_receipt_advice.REMARK
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.REMARK
     *
     * @param remark the value for pj_fa_receipt_advice.REMARK
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setRemark(String remark) {
        if (remark != null) {
            remark = remark.trim();
        }
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.OPERATOR_ID
     *
     * @return the value of pj_fa_receipt_advice.OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.OPERATOR_ID
     *
     * @param operatorId the value for pj_fa_receipt_advice.OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setOperatorId(String operatorId) {
        if (operatorId != null) {
            operatorId = operatorId.trim();
        }
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CREATED_DATE
     *
     * @return the value of pj_fa_receipt_advice.CREATED_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CREATED_DATE
     *
     * @param createdDate the value for pj_fa_receipt_advice.CREATED_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CONFIRM_OPERATOR_ID
     *
     * @return the value of pj_fa_receipt_advice.CONFIRM_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getConfirmOperatorId() {
        return confirmOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CONFIRM_OPERATOR_ID
     *
     * @param confirmOperatorId the value for pj_fa_receipt_advice.CONFIRM_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setConfirmOperatorId(String confirmOperatorId) {
        if (confirmOperatorId != null) {
            confirmOperatorId = confirmOperatorId.trim();
        }
        this.confirmOperatorId = confirmOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CONFIRM_DATE
     *
     * @return the value of pj_fa_receipt_advice.CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CONFIRM_DATE
     *
     * @param confirmDate the value for pj_fa_receipt_advice.CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CANCEL_OPERATOR_ID
     *
     * @return the value of pj_fa_receipt_advice.CANCEL_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getCancelOperatorId() {
        return cancelOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CANCEL_OPERATOR_ID
     *
     * @param cancelOperatorId the value for pj_fa_receipt_advice.CANCEL_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCancelOperatorId(String cancelOperatorId) {
        if (cancelOperatorId != null) {
            cancelOperatorId = cancelOperatorId.trim();
        }
        this.cancelOperatorId = cancelOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.CANCEL_DATE
     *
     * @return the value of pj_fa_receipt_advice.CANCEL_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.CANCEL_DATE
     *
     * @param cancelDate the value for pj_fa_receipt_advice.CANCEL_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_OPERATOR_ID
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getFactorOperatorId() {
        return factorOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_OPERATOR_ID
     *
     * @param factorOperatorId the value for pj_fa_receipt_advice.FACTOR_OPERATOR_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorOperatorId(String factorOperatorId) {
        if (factorOperatorId != null) {
            factorOperatorId = factorOperatorId.trim();
        }
        this.factorOperatorId = factorOperatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_CONFIRM_DATE
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public Date getFactorConfirmDate() {
        return factorConfirmDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_CONFIRM_DATE
     *
     * @param factorConfirmDate the value for pj_fa_receipt_advice.FACTOR_CONFIRM_DATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorConfirmDate(Date factorConfirmDate) {
        this.factorConfirmDate = factorConfirmDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FACTOR_UNCONFIRM_REASON
     *
     * @return the value of pj_fa_receipt_advice.FACTOR_UNCONFIRM_REASON
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getFactorUnconfirmReason() {
        return factorUnconfirmReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FACTOR_UNCONFIRM_REASON
     *
     * @param factorUnconfirmReason the value for pj_fa_receipt_advice.FACTOR_UNCONFIRM_REASON
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFactorUnconfirmReason(String factorUnconfirmReason) {
        if (factorUnconfirmReason != null) {
            factorUnconfirmReason = factorUnconfirmReason.trim();
        }
        this.factorUnconfirmReason = factorUnconfirmReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO1
     *
     * @return the value of pj_fa_receipt_advice.ATTACHMENT_INFO1
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getAttachmentInfo1() {
        return attachmentInfo1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO1
     *
     * @param attachmentInfo1 the value for pj_fa_receipt_advice.ATTACHMENT_INFO1
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo1(String attachmentInfo1) {
        if (attachmentInfo1 != null) {
            attachmentInfo1 = attachmentInfo1.trim();
        }
        this.attachmentInfo1 = attachmentInfo1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO2
     *
     * @return the value of pj_fa_receipt_advice.ATTACHMENT_INFO2
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getAttachmentInfo2() {
        return attachmentInfo2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO2
     *
     * @param attachmentInfo2 the value for pj_fa_receipt_advice.ATTACHMENT_INFO2
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo2(String attachmentInfo2) {
        if (attachmentInfo2 != null) {
            attachmentInfo2 = attachmentInfo2.trim();
        }
        this.attachmentInfo2 = attachmentInfo2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO3
     *
     * @return the value of pj_fa_receipt_advice.ATTACHMENT_INFO3
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public String getAttachmentInfo3() {
        return attachmentInfo3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.ATTACHMENT_INFO3
     *
     * @param attachmentInfo3 the value for pj_fa_receipt_advice.ATTACHMENT_INFO3
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setAttachmentInfo3(String attachmentInfo3) {
        if (attachmentInfo3 != null) {
            attachmentInfo3 = attachmentInfo3.trim();
        }
        this.attachmentInfo3 = attachmentInfo3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.INTEREST_RATE
     *
     * @return the value of pj_fa_receipt_advice.INTEREST_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.INTEREST_RATE
     *
     * @param interestRate the value for pj_fa_receipt_advice.INTEREST_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setInterestRate(long interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.FEE_RATE
     *
     * @return the value of pj_fa_receipt_advice.FEE_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.FEE_RATE
     *
     * @param feeRate the value for pj_fa_receipt_advice.FEE_RATE
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setFeeRate(long feeRate) {
        this.feeRate = feeRate;
    }
}
