package com.hstd.exchange.entity.model;


public class FaReceiptAdviceKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column pj_fa_receipt_advice.RECEIPT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    private long receiptAdviceId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column pj_fa_receipt_advice.RECEIPT_ADVICE_ID
     *
     * @return the value of pj_fa_receipt_advice.RECEIPT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public long getReceiptAdviceId() {
        return receiptAdviceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column pj_fa_receipt_advice.RECEIPT_ADVICE_ID
     *
     * @param receiptAdviceId the value for pj_fa_receipt_advice.RECEIPT_ADVICE_ID
     *
     * @abatorgenerated Tue Dec 19 21:46:06 CST 2017
     */
    public void setReceiptAdviceId(long receiptAdviceId) {
        this.receiptAdviceId = receiptAdviceId;
    }
}
